AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for deploying a lambda function
Parameters:
  EnvironmentName:
    Type: String
    Description: Used in resource naming to associate resources with a stack
Resources:
  ChromiumLambdaDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-lambda-dependencies
      Description: Dependencies chromium-lambda
      ContentUri: s3://deployment.us-west-2/chromium-lambda-dependencies-test-us-west-2/cd94dc8880c062a02fa3a537005f3be4
      CompatibleRuntimes:
      - nodejs12.x
      LicenseInfo: Apache2.0
      RetentionPolicy: Retain
